In [59]:
import pandas as pd

df = pd.read_csv('Golf.csv')
df = df.drop(columns = 'Unnamed: 0')
df

     Outlook Temperature Humidity   Windy Play Golf
0      Rainy         Hot     High  False         No
1      Rainy         Hot     High   True         No
2   Overcast         Hot     High  False        Yes
3      Sunny        Mild     High  False        Yes
4      Sunny        Cool   Normal  False        Yes
5      Sunny        Cool   Normal   True         No
6   Overcast        Cool   Normal   True        Yes
7      Rainy        Mild     High  False         No
8      Rainy        Cool   Normal  False        Yes
9      Sunny        Mild   Normal  False        Yes
10     Rainy        Mild   Normal   True        Yes
11  Overcast        Mild     High   True        Yes
12  Overcast         Hot   Normal  False        Yes
13     Sunny        Mild     High   True         No

In [61]:
from sklearn.naive_bayes import GaussianNB
import numpy as np

# Define the training data
# outlook: sunny=0, overcast=1, rainy=2
# temperature: hot=0, mild=1, cool=2
# humidity: high=0, normal=1
# wind: strong=0, weak=1

df = df.replace({'Outlook': {'Sunny': 0, 'Overcast': 1, 'Rainy': 2},
                 'Temperature': {'Hot': 0, 'Mild': 1, 'Cool': 2},
                 'Humidity': {'High': 0, 'Normal': 1}})
df = df.replace({'Windy' : {'False ': 0, 'True ': 1}})
X_train = df.drop(columns = 'Play Golf')
X_train = X_train.to_numpy()
X_train

array([[2, 0, 0, 0],
       [2, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 2, 1, 0],
       [0, 2, 1, 1],
       [1, 2, 1, 1],
       [2, 1, 0, 0],
       [2, 2, 1, 0],
       [0, 1, 1, 0],
       [2, 1, 1, 1],
       [1, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1]])

In [62]:
# Define the target labels
y_train = np.array([x for x in df['Play Golf']])

In [68]:
# Create a Gaussian Naive Bayes model and fit the data
gnb = GaussianNB()
gnb.fit(X_train, y_train)

# Define the input parameters for prediction
# outlook: sunny=0, overcast=1, rainy=2
# temperature: hot=0, mild=1, cool=2
# humidity: high=0, normal=1
# wind: strong=0, weak=1
X_test = np.array([[1, 1, 0, 0]])

# Make a prediction using the trained model
y_pred = gnb.predict(X_test)

# Print the prediction
print('The model predicts that the answer is:', y_pred[0])

The model predicts that the answer is: Yes